apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${email_address}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: ${domain}-wildcard-key

    # ACME DNS-01 provider configurations
    dns01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:
        - name: gcp
          clouddns:
            # The ID of the GCP project
            project: ${google_project}
            # This is the secret used to access the service account
            serviceAccountSecretRef:
              name: clouddns-private-key
              key: credentials.json
